install:
  - wget -nv https://download.java.net/java/GA/jdk17.0.1/2a2082e5a09d4267845be086888add4f/12/GPL/openjdk-17.0.1_linux-x64_bin.tar.gz -O jdk17.tar.gz
  - mkdir -p ~/jdk17
  - tar -xf jdk17.tar.gz -C ~/jdk17 --strip-components=1

  - echo 'export JAVA_HOME=$HOME/jdk17' >> ~/.bashrc
  - echo 'export PATH=$JAVA_HOME/bin:$PATH' >> ~/.bashrc
  - echo 'export JAVA_HOME=$HOME/jdk17' >> ~/.profile
  - echo 'export PATH=$JAVA_HOME/bin:$PATH' >> ~/.profile

  - export JAVA_HOME=$HOME/jdk17
  - export PATH=$JAVA_HOME/bin:$PATH
  - java -version

script:
  - export JAVA_HOME=$HOME/jdk17
  - export PATH=$JAVA_HOME/bin:$PATH
  - java -version
  - ./gradlew listDeps -I ../deps.gradle
